### ISSUE TITLE
Problems about inline image url 

### ISSUE THREAD

**Issue by ja67** [JohnMcLear/ep_previewimages#5]
I found that if I input something after the url of an inserted image at the same line, there will be some empty lines added before the image. I was also wondering if there is a way to hide the image url and delete the image like other editors by simply press backspace after the image other deleting the url. Thanks!

**Comment by JohnMcLear** [comment]
@ja67 check out https://github.com/JohnMcLear/ep_copy_paste_images -- is this a better solution for you?

**Comment by JohnMcLear** [comment]
Confirmed bug, will try take a look at this ASAP

**Comment by JohnMcLear** [comment]
Fixed and published update.
