### ISSUE TITLE
ep_previewimages plugin has a lot of discrepancies.

### ISSUE THREAD

**Issue by akshat-g** [JohnMcLear/ep_previewimages#9]
Whenever I hit enter just after the URL of the image, the etherpad instance gets disconnected.The error is like this - 
           ``newline count is wrong in op =; cs:Z:8s>1|5=6b=2g*0|1+1$``

I guess there is some changeset problem with the no. of lines which are already present on the etherpad instance. Also I also do not want URL of the image below it. I also check ep_copy_paste_iamges plugin but it also did not work in Chrome.It just the pasted the image URL.
In ep_previewimages how should I make normal backspace work.Whenever I hit backspace on the image, the image does not get deleted but rather something weird happens and whole of the changeset gets screwed up.

**Comment by JohnMcLear** [comment]
I'm unable to replicate this in Firefox or Chrome.

If you have multiple things to file issues about please create multiple issues.
